import type { Metadata } from "next";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import "bootstrap/dist/css/bootstrap.min.css";
import { ContractProvider } from "./contract/[id]/api/useContract";

export const metadata: Metadata = {
  title: "Las Vegas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ContractProvider>
            {children}
          </ContractProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
